### ISSUE TITLE
Ekran konfiguracji

### ISSUE THREAD

**Issue by cole1911** [cole1911/uam-email-client#9]
Ma działać wg. specyfikacji:

https://onedrive.live.com/view.aspx?resid=21310A5E53BCBECB!25945&ithint=file%2cdocx&app=Word&authkey=!AIXhVkzmK7SQ34k

**Comment by gregory16mix** [comment]
Wykonane razem z Damianem :) 
Kod przekazany mailem z powodu używania laptopa służbowego. Blokada używania Git'a.
